/* ============================================================
   VAULT22 INVESTOR LEADERBOARD - data model
   All figures are MOCK / ILLUSTRATIVE for design prototyping.
   "Inspired By" model portfolios are educational, not official
   portfolios of any named investor. Not financial advice.
   ============================================================ */

/* palette used by charts (assigned by index) */
const PIE_COLORS = ['#00C389','#4FC3F7','#7C6CFF','#E7C27D','#FF7A9A','#FBBF24','#34D399','#38BDF8','#A78BFA','#F472B6'];

/* ---------- the signed-in user (mock) ---------- */
const USER = {
  name:'Aishani Atri', initials:'AA',
  dna:{
    style:'Balanced Builder',
    riskProfile:'Moderate', riskScore:58,
    horizon:'Long term (7+ yrs)',
    diversification:64,
    consistency:72,
    behaviour:81,
    summary:'You invest steadily with a moderate risk appetite, favour diversified core holdings and rarely react to short-term volatility. Your edge is discipline, not timing. Tara suggests widening geographic exposure and trimming concentration in tech.',
    traits:[['Risk appetite','Moderate',58],['Diversification','Developing',64],['Discipline','Strong',81],['Time horizon','Long',88]]
  },
  /* mock current portfolio for overlap + compare */
  allocation:[{k:'US Equities',v:46},{k:'Global Equities',v:18},{k:'Bonds',v:14},{k:'Crypto',v:10},{k:'Cash',v:12}],
  sectors:[{k:'Technology',v:34},{k:'Financials',v:16},{k:'Healthcare',v:12},{k:'Consumer',v:14},{k:'Energy',v:8},{k:'Other',v:16}],
  geo:[{k:'North America',v:64},{k:'Europe',v:14},{k:'Asia-Pacific',v:12},{k:'Emerging',v:10}],
  mcap:[{k:'Mega cap',v:52},{k:'Large cap',v:26},{k:'Mid cap',v:14},{k:'Small cap',v:8}],
  holdings:[{n:'Apple',v:9},{n:'S&P 500 ETF',v:22},{n:'Microsoft',v:7},{n:'Global ETF',v:18},{n:'Bitcoin',v:7},{n:'Aggregate Bond ETF',v:14},{n:'Cash',v:12},{n:'Others',v:11}],
  risk:{sharpe:0.94,vol:12.4,maxDD:-18.2,beta:0.97},
  seed:71
};

/* ---------- educational metric definitions (tooltips + AI) ---------- */
const METRICS = {
  'Risk-adjusted return':{d:'Return earned per unit of risk taken, not raw return. Rewards investors who made steady gains without wild swings.',tara:'A high raw return with huge volatility can score worse than a calmer, smaller return. This is how we avoid crowning lucky gamblers.'},
  'Sharpe Ratio':{d:'Return above the risk-free rate divided by volatility. Above 1.0 is good, above 2.0 is excellent.',tara:'Think of it as return quality. Two investors both made 12%, but the one with the higher Sharpe did it with far less white-knuckle risk.'},
  'Max drawdown':{d:'The largest peak-to-trough fall the portfolio ever suffered. Shows the worst pain an investor lived through.',tara:'Ask yourself honestly: could you hold through a drop this deep without panic selling? That is the real test of a style.'},
  'Volatility':{d:'How much the portfolio value swings up and down, shown as annualised standard deviation. Lower means a smoother ride.',tara:'Volatility is not the same as loss, but high volatility is where most people make emotional mistakes.'},
  'Consistency Score':{d:'How reliably an investor delivers across many periods rather than one lucky year. Higher means dependable, not spiky.',tara:'Consistency compounds. A dependable 9% a year beats a 40% year followed by a 30% collapse.'},
  'Behaviour Score':{d:'Rewards good habits: staying invested through corrections, regular contributions and avoiding panic selling.',tara:'This is the metric most platforms hide. Behaviour, not stock picking, is what separates most outcomes over a decade.'},
  'Diversification Score':{d:'How well risk is spread across assets, sectors and regions. Higher means less exposed to any single shock.',tara:'Concentration builds wealth, diversification keeps it. A balanced score suits most long-term investors.'},
  'Portfolio Overlap':{d:'The share of holdings you already own that this investor also holds. High overlap means fewer changes to adopt the style.',tara:'High overlap means adopting this style is a small tilt, not a rebuild. Low overlap means bigger changes and bigger tax or fee impact.'},
  'AI Match %':{d:'How well this style fits your Investor DNA: risk profile, horizon, diversification and existing holdings.',tara:'Match is about fit, not quality. A brilliant aggressive style can be a poor match if your DNA is conservative.'}
};

/* ---------- gamification badges ---------- */
const BADGES = [
  {i:'🛡️',t:'Stayed Invested During Correction',d:'Held through a 10%+ market drop without selling',earned:true},
  {i:'📅',t:'Monthly Contribution Streak',d:'11 months of consistent contributions',earned:true,prog:'11 / 12'},
  {i:'🌐',t:'Diversification Expert',d:'Spread across 4+ asset classes and 3+ regions',earned:true},
  {i:'⚖️',t:'Disciplined Rebalancer',d:'Rebalanced on schedule, not on emotion',earned:false,prog:'2 / 3 rebalances'},
  {i:'🌱',t:'Long-Term Investor',d:'Held core positions for 3+ years',earned:true},
  {i:'🧭',t:'Risk Manager',d:'Kept portfolio drawdown within your risk plan',earned:false,prog:'On track'}
];

/* helper to build a legend/investor record compactly */
function L(o){ o.inspired=true; return o; }

/* ============================================================
   MARKET LEGENDS - 20 TradFi "Inspired By" model styles
   Holdings/allocations are illustrative of the STYLE.
   `src` = where the real style / disclosed holdings can be verified.
   ============================================================ */
const TRADFI = [
 L({id:'buffett',name:'Warren Buffett',style:'Quality Value',cat:'tradfi',initials:'WB',c1:'#E7C27D',c2:'#C9A24B',
   ret3y:12.4,maxDD:-24,vol:14,consistency:94,riskAdj:0.98,risk:'Moderate',hold:'10+ years',horizon:'10+ years',
   bio:'Chair of Berkshire Hathaway and the most studied value investor of the modern era, known for buying wonderful businesses at fair prices and holding for decades.',
   philosophy:'Own cash-generative, competitively durable businesses bought below intrinsic value, then let them compound. Be fearful when others are greedy.',
   hist:'Low turnover, concentrated, heavy in insurance, consumer brands and banks. Historically defensive in crashes, can lag in speculative bull runs.',
   sectors:['Technology','Financials','Consumer Staples','Energy'],
   alloc:[{k:'US Large-cap Equity',v:80},{k:'Cash & T-bills',v:16},{k:'Other',v:4}],
   holdings:[{n:'Apple',v:26},{n:'American Express',v:15},{n:'Bank of America',v:11},{n:'Coca-Cola',v:9},{n:'Chevron',v:7},{n:'Cash / T-bills',v:16},{n:'Others',v:16}],
   suit:'Patient investors who want durable compounding and can ignore short-term noise.',
   avoid:'Anyone chasing fast gains or who needs the money within a few years.',
   tara:'Buffett-style portfolios usually underperform in hype-driven markets but aim to compound quietly over decades. Suits your long horizon, though it is more concentrated than your current mix.',
   src:'Berkshire Hathaway 13F filings, SEC EDGAR (latest disclosed top holdings: Apple, American Express, Bank of America, Coca-Cola, Chevron).'}),
 L({id:'munger',name:'Charlie Munger',style:'Concentrated Quality',cat:'tradfi',initials:'CM',c1:'#B0BEC5',c2:'#78909C',
   ret3y:11.1,maxDD:-27,vol:15,consistency:88,riskAdj:0.9,risk:'Moderate-High',hold:'10+ years',horizon:'10+ years',
   bio:'Berkshire vice-chair and Buffett\'s intellectual partner, an advocate of extreme patience and a handful of high-conviction bets.',
   philosophy:'A small number of great companies held forever beats constant activity. Sit on quality and do nothing.',
   hist:'Very concentrated, tolerant of volatility, willing to hold just a few names. Higher single-stock risk than a broad index.',
   sectors:['Financials','Technology','Consumer'],
   alloc:[{k:'Global Equity',v:88},{k:'Cash',v:12}],
   holdings:[{n:'Bank of America',v:24},{n:'Wells Fargo',v:18},{n:'Alibaba',v:16},{n:'US Bancorp',v:14},{n:'Berkshire',v:16},{n:'Cash',v:12}],
   suit:'Conviction investors comfortable with few holdings and real volatility.',
   avoid:'Investors who need a smooth ride or broad diversification.',
   tara:'This is Buffett dialled up: fewer names, more conviction. Higher single-stock risk than suits a Balanced Builder, so consider the Conservative tilt.',
   src:'Munger\'s Daily Journal Corp 13F filings, SEC EDGAR; public commentary at Berkshire and Daily Journal meetings.'}),
 L({id:'wood',name:'Cathie Wood',style:'Disruptive Innovation',cat:'tradfi',initials:'CW',c1:'#FF7A9A',c2:'#E14D6E',
   ret3y:6.8,maxDD:-67,vol:38,consistency:41,riskAdj:0.32,risk:'Very High',hold:'5-7 years',horizon:'7+ years',
   bio:'Founder of ARK Invest, a high-conviction backer of disruptive innovation across AI, genomics, robotics and fintech.',
   philosophy:'Concentrate in exponential technologies that reshape the world over five-plus years, accepting deep drawdowns for outsized upside.',
   hist:'Extremely volatile, big swings, spectacular in innovation bull markets and brutal drawdowns when rates rise. Not for the faint-hearted.',
   sectors:['Technology','Healthcare/Genomics','Fintech','Robotics'],
   alloc:[{k:'Innovation Equity',v:96},{k:'Cash',v:4}],
   holdings:[{n:'Tesla',v:12},{n:'Coinbase',v:9},{n:'Roku',v:7},{n:'Block',v:6},{n:'CRISPR / genomics basket',v:14},{n:'AI & robotics basket',v:28},{n:'Others',v:24}],
   suit:'Aggressive, long-horizon investors who can stomach 50%+ drops for a shot at high growth.',
   avoid:'Anyone who panic sells, or needs stability and income.',
   tara:'Warning: this style has historically doubled and halved. It scores a low match for your DNA. If you want a taste, size it small and pair it with the Defensive Allocation strategy.',
   src:'ARK Invest ARKK holdings, published daily on ark-invest.com; ARKK objective is long-term growth via disruptive innovation.'}),
 L({id:'dalio',name:'Ray Dalio',style:'All-Weather Risk Parity',cat:'tradfi',initials:'RD',c1:'#4FC3F7',c2:'#2196F3',
   ret3y:6.2,maxDD:-20,vol:9,consistency:86,riskAdj:0.72,risk:'Low-Moderate',hold:'Perpetual',horizon:'5+ years',
   bio:'Founder of Bridgewater Associates, the world\'s largest hedge fund, and author of the All-Weather / risk-parity framework.',
   philosophy:'Balance risk across assets that thrive in different economic seasons, so no single environment can sink the portfolio.',
   hist:'Smooth ride, lower volatility, designed to weather inflation, deflation, growth and recession. Gives up some upside for resilience.',
   sectors:['Broad diversified'],
   alloc:[{k:'Long-term Bonds',v:40},{k:'US Equity',v:30},{k:'Intermediate Bonds',v:15},{k:'Gold',v:7.5},{k:'Commodities',v:7.5}],
   holdings:[{n:'Long-term Treasuries',v:40},{n:'Total US Stock',v:30},{n:'Intermediate Treasuries',v:15},{n:'Gold',v:8},{n:'Broad Commodities',v:7}],
   suit:'Investors who value a smooth ride and want protection across economic climates.',
   avoid:'Investors chasing maximum growth in a bull market.',
   tara:'A strong match for your discipline. This would lower your volatility and add inflation protection your current mix lacks. A sensible core to build around.',
   src:'Bridgewater All Weather framework; the public "All Seasons" allocation popularised in Tony Robbins\' Money: Master the Game.'}),
 L({id:'lynch',name:'Peter Lynch',style:'Growth At Reasonable Price',cat:'tradfi',initials:'PL',c1:'#34D399',c2:'#059669',
   ret3y:13.1,maxDD:-30,vol:18,consistency:79,riskAdj:0.86,risk:'Moderate-High',hold:'3-6 years',horizon:'5+ years',
   bio:'Legendary manager of Fidelity\'s Magellan Fund, who averaged roughly 29% a year over 13 years by buying what he understood.',
   philosophy:'Invest in what you know, favour growing companies at reasonable valuations, and let winners run into multi-baggers.',
   hist:'Diversified across many growth names, moderate volatility, strong in expansions. Requires ongoing research.',
   sectors:['Consumer','Retail','Industrials','Technology'],
   alloc:[{k:'US Equity',v:85},{k:'International Equity',v:10},{k:'Cash',v:5}],
   holdings:[{n:'Consumer growth basket',v:30},{n:'Retail leaders',v:20},{n:'Industrials',v:15},{n:'Tech growth',v:20},{n:'International',v:10},{n:'Cash',v:5}],
   suit:'Hands-on investors who enjoy research and want growth without paying bubble prices.',
   avoid:'Passive investors who do not want to monitor holdings.',
   tara:'A good fit for your growth tilt without the extreme risk of pure innovation styles. Pairs well with a low-cost index core.',
   src:'Peter Lynch\'s approach documented in One Up on Wall Street and Beating the Street; Fidelity Magellan track record.'}),
 L({id:'graham',name:'Benjamin Graham',style:'Deep Value',cat:'tradfi',initials:'BG',c1:'#90A4AE',c2:'#546E7A',
   ret3y:9.4,maxDD:-22,vol:13,consistency:84,riskAdj:0.83,risk:'Moderate',hold:'2-5 years',horizon:'5+ years',
   bio:'The father of value investing and Buffett\'s mentor, author of Security Analysis and The Intelligent Investor.',
   philosophy:'Buy with a margin of safety far below intrinsic value, diversify across bargains, and let the market\'s pessimism become your entry.',
   hist:'Value-tilted, defensive, cheaper valuations. Can lag growth for long stretches then snap back.',
   sectors:['Financials','Industrials','Value equities'],
   alloc:[{k:'Value Equity',v:60},{k:'Bonds',v:35},{k:'Cash',v:5}],
   holdings:[{n:'Deep-value equity basket',v:60},{n:'Investment-grade bonds',v:35},{n:'Cash',v:5}],
   suit:'Cautious value investors who want a built-in margin of safety.',
   avoid:'Growth chasers who cannot wait for value to be recognised.',
   tara:'A classic 60/40-ish value core. Lower risk than your current mix and a good anchor if markets feel expensive.',
   src:'Benjamin Graham\'s The Intelligent Investor; the defensive investor allocation (equities/bonds within 25-75% bands).'}),
 L({id:'bogle',name:'John Bogle',style:'Low-Cost Index Core',cat:'tradfi',initials:'JB',c1:'#00C389',c2:'#009E70',
   ret3y:10.2,maxDD:-24,vol:14,consistency:90,riskAdj:0.9,risk:'Moderate',hold:'Perpetual',horizon:'10+ years',
   bio:'Founder of Vanguard and inventor of the index fund, who showed that owning the whole market cheaply beats most active managers.',
   philosophy:'Do not look for the needle, buy the haystack. Minimise costs, hold the total market and stay the course.',
   hist:'Broad, cheap, tax-efficient, market-matching. The lowest-maintenance core there is.',
   sectors:['Whole market'],
   alloc:[{k:'Total US Stock',v:54},{k:'Total International Stock',v:18},{k:'Total Bond',v:28}],
   holdings:[{n:'Total US Stock Market',v:54},{n:'Total International Stock',v:18},{n:'Total Bond Market',v:28}],
   suit:'Almost everyone as a core. Ideal for low-cost, hands-off, long-term wealth building.',
   avoid:'Investors seeking to beat the market rather than match it.',
   tara:'The strongest match for your DNA. This is the low-cost three-fund core most long-term plans should be built on. Adopting it would improve your diversification score.',
   src:'The Bogleheads three-fund portfolio; Vanguard total-market index funds and John Bogle\'s The Little Book of Common Sense Investing.'}),
 L({id:'sixtyforty',name:'BlackRock 60/40',style:'Balanced Model',cat:'tradfi',initials:'60',c1:'#607D8B',c2:'#455A64',
   ret3y:8.1,maxDD:-21,vol:11,consistency:88,riskAdj:0.82,risk:'Moderate',hold:'Perpetual',horizon:'5+ years',
   bio:'The classic institutional balanced allocation, offered as a model portfolio by managers such as BlackRock.',
   philosophy:'Sixty percent global equities for growth, forty percent bonds for stability. Rebalance and repeat.',
   hist:'The industry benchmark for balanced investing. Steady, well understood, moderate drawdowns.',
   sectors:['Diversified'],
   alloc:[{k:'Global Equity',v:60},{k:'Global Bonds',v:40}],
   holdings:[{n:'Global Equity ETF',v:45},{n:'US Equity ETF',v:15},{n:'Aggregate Bond ETF',v:28},{n:'Government Bond ETF',v:12}],
   suit:'Investors who want a proven, balanced default without decisions.',
   avoid:'Those who want higher growth and can handle more risk.',
   tara:'A near-perfect match for a Balanced Builder. Compared with your portfolio it adds bond ballast and trims your crypto and cash drag.',
   src:'BlackRock 60/40 target-allocation model portfolios; a standard global balanced benchmark.'}),
 L({id:'islamic',name:'Islamic Growth',style:'Shariah Equities & Sukuk',cat:'tradfi',initials:'☪',c1:'#00C389',c2:'#00E0A0',shariah:true,
   ret3y:9.6,maxDD:-23,vol:13,consistency:82,riskAdj:0.84,risk:'Moderate',hold:'5+ years',horizon:'7+ years',
   bio:'A Shariah-screened growth model excluding interest-based finance, alcohol, gambling and other non-compliant sectors, balanced with sukuk.',
   philosophy:'Compound within faith-based screens: quality Shariah equities for growth and sukuk for income and stability.',
   hist:'Naturally underweight banks, overweight tech, healthcare and industrials. Purification of incidental income applies.',
   sectors:['Technology','Healthcare','Industrials','Materials'],
   alloc:[{k:'Shariah Global Equity',v:70},{k:'Sukuk',v:22},{k:'Cash',v:8}],
   holdings:[{n:'Shariah global equity fund',v:45},{n:'Shariah US equity',v:25},{n:'Sukuk (Islamic bonds)',v:22},{n:'Cash',v:8}],
   suit:'Investors who want growth within Shariah-compliant screens.',
   avoid:'Those needing exposure to conventional banking or income from interest.',
   tara:'Fully Shariah-compliant and well diversified. If faith-based screening matters to you, this is a stronger core than your current mix, which holds conventional financials.',
   src:'S&P Dow Jones and MSCI Islamic index methodologies (AAOIFI-based screens); sukuk indices such as the S&P MENA Sukuk.'}),
 L({id:'soros',name:'George Soros',style:'Global Macro',cat:'tradfi',initials:'GS',c1:'#7C6CFF',c2:'#5B47FB',
   ret3y:9.9,maxDD:-33,vol:22,consistency:58,riskAdj:0.55,risk:'High',hold:'Months-2 years',horizon:'5+ years',
   bio:'Founder of the Quantum Fund, famous for macro bets including breaking the Bank of England in 1992.',
   philosophy:'Markets are driven by reflexive feedback loops. Take large, asymmetric macro positions when conviction and mispricing align.',
   hist:'Opportunistic, uses leverage and derivatives, can move sharply between assets. High skill required, not a set-and-forget style.',
   sectors:['Macro / multi-asset'],
   alloc:[{k:'Equity',v:55},{k:'Fixed income',v:20},{k:'Currencies/Macro',v:15},{k:'Cash',v:10}],
   holdings:[{n:'US equity basket',v:40},{n:'International equity',v:15},{n:'Bonds',v:20},{n:'Macro / FX positions',v:15},{n:'Cash',v:10}],
   suit:'Sophisticated investors comfortable with macro risk and active management.',
   avoid:'Passive or risk-averse investors.',
   tara:'Macro styles depend heavily on manager skill and are hard to replicate faithfully. A low match for a disciplined long-term builder. Educational value is high, allocation should be small.',
   src:'Soros Fund Management 13F filings, SEC EDGAR; strategy documented in The Alchemy of Finance.'}),
 L({id:'druck',name:'Stanley Druckenmiller',style:'Concentrated Macro',cat:'tradfi',initials:'SD',c1:'#38BDF8',c2:'#0284C7',
   ret3y:12.8,maxDD:-28,vol:20,consistency:70,riskAdj:0.74,risk:'High',hold:'6 months-3 years',horizon:'5+ years',
   bio:'Former lead manager for Soros and founder of Duquesne, who never had a down year over three decades.',
   philosophy:'Concentrate hard when you have an edge, and preserve capital fiercely when you do not. Bet big or stay in cash.',
   hist:'Flexible, concentrated, rotates aggressively between growth, macro and cash. Strong capital preservation instinct.',
   sectors:['Technology','Macro','Consumer'],
   alloc:[{k:'Equity',v:65},{k:'Fixed income',v:15},{k:'Cash',v:20}],
   holdings:[{n:'Mega-cap tech basket',v:30},{n:'Growth equity',v:20},{n:'Healthcare',v:15},{n:'Bonds',v:15},{n:'Cash',v:20}],
   suit:'Active investors who can size conviction and hold high cash when unsure.',
   avoid:'Investors who dislike large cash positions or concentration.',
   tara:'Druckenmiller keeps a lot of dry powder, which your DNA would appreciate. Still concentrated, so treat as a satellite, not a core.',
   src:'Duquesne Family Office 13F filings, SEC EDGAR; interviews and public commentary.'}),
 L({id:'marks',name:'Howard Marks',style:'Credit & Distressed Value',cat:'tradfi',initials:'HM',c1:'#E7C27D',c2:'#B8860B',
   ret3y:8.7,maxDD:-19,vol:12,consistency:85,riskAdj:0.82,risk:'Moderate',hold:'3-7 years',horizon:'5+ years',
   bio:'Co-founder of Oaktree Capital, the leading distressed-debt investor and author of widely read memos on risk and cycles.',
   philosophy:'You cannot predict, but you can prepare. Buy debt and assets when fear is highest and price is well below value.',
   hist:'Credit-heavy, contrarian, buys in downturns. Lower equity volatility, income-oriented, patient.',
   sectors:['Credit','High yield','Distressed'],
   alloc:[{k:'Corporate & High-yield Credit',v:55},{k:'Distressed / Special sit.',v:20},{k:'Equity',v:15},{k:'Cash',v:10}],
   holdings:[{n:'High-yield credit',v:35},{n:'Investment-grade credit',v:20},{n:'Distressed basket',v:20},{n:'Equity',v:15},{n:'Cash',v:10}],
   suit:'Income-focused investors who want a contrarian, credit-led approach.',
   avoid:'Investors seeking pure equity growth.',
   tara:'A useful income and diversification tilt away from your equity-heavy mix. Credit behaves differently from stocks, which can smooth your ride.',
   src:'Oaktree Capital strategy and Howard Marks\' public memos at oaktreecapital.com; documented in The Most Important Thing.'}),
 L({id:'greenblatt',name:'Joel Greenblatt',style:'Magic Formula Value',cat:'tradfi',initials:'JG',c1:'#34D399',c2:'#10B981',
   ret3y:11.6,maxDD:-26,vol:16,consistency:78,riskAdj:0.85,risk:'Moderate-High',hold:'1-3 years',horizon:'5+ years',
   bio:'Founder of Gotham Capital and creator of the Magic Formula, a systematic way to buy good companies cheaply.',
   philosophy:'Rank companies by earnings yield and return on capital, buy the best combinations, and rebalance on a rules-based schedule.',
   hist:'Systematic value, diversified across dozens of names, requires periodic rebalancing. Can underperform value-out-of-favour years.',
   sectors:['Value','Industrials','Consumer'],
   alloc:[{k:'US Value Equity',v:90},{k:'Cash',v:10}],
   holdings:[{n:'High earnings-yield basket',v:50},{n:'High return-on-capital basket',v:40},{n:'Cash',v:10}],
   suit:'Rules-based investors who want value exposure without stock picking.',
   avoid:'Investors who dislike periodic rebalancing or value droughts.',
   tara:'A disciplined, systematic value tilt that suits your rules-driven side. Best as a value satellite alongside an index core.',
   src:'Joel Greenblatt\'s The Little Book That Still Beats the Market; the Magic Formula ranking methodology.'}),
 L({id:'swensen',name:'David Swensen',style:'Yale Endowment Model',cat:'tradfi',initials:'DS',c1:'#4FC3F7',c2:'#1E88E5',
   ret3y:9.1,maxDD:-20,vol:11,consistency:87,riskAdj:0.84,risk:'Moderate',hold:'Perpetual',horizon:'10+ years',
   bio:'The late CIO of Yale, who pioneered the endowment model with heavy diversification into alternatives.',
   philosophy:'Diversify broadly across equity-like assets including real assets, and harvest illiquidity and rebalancing premiums.',
   hist:'Well diversified, includes real assets, low correlation between sleeves. Designed for very long horizons.',
   sectors:['Diversified / Real assets'],
   alloc:[{k:'US Equity',v:30},{k:'International Equity',v:20},{k:'Emerging Equity',v:10},{k:'REITs / Real assets',v:20},{k:'Bonds & TIPS',v:20}],
   holdings:[{n:'US Total Stock',v:30},{n:'Developed International',v:20},{n:'Emerging Markets',v:10},{n:'REITs',v:20},{n:'Treasuries + TIPS',v:20}],
   suit:'Long-horizon investors who want institutional-grade diversification.',
   avoid:'Short-term investors or those wanting simplicity.',
   tara:'A superb match for your long horizon. It adds real assets and international exposure your portfolio is light on. A strong candidate for your core.',
   src:'David Swensen\'s Unconventional Success; the retail "Yale/Swensen" model allocation for individual investors.'}),
 L({id:'klarman',name:'Seth Klarman',style:'Margin Of Safety',cat:'tradfi',initials:'SK',c1:'#90A4AE',c2:'#607D8B',
   ret3y:8.4,maxDD:-16,vol:10,consistency:89,riskAdj:0.82,risk:'Low-Moderate',hold:'3-7 years',horizon:'5+ years',
   bio:'Founder of the Baupost Group, a famously cautious value investor who holds large cash balances until bargains appear.',
   philosophy:'Absolute-return value: protect capital first, hold cash patiently, and buy only with a wide margin of safety.',
   hist:'High cash, low volatility, opportunistic. Sacrifices upside in bull markets to avoid permanent loss.',
   sectors:['Value','Special situations'],
   alloc:[{k:'Value Equity',v:50},{k:'Special situations',v:20},{k:'Cash',v:30}],
   holdings:[{n:'Deep-value equity',v:35},{n:'Special situations',v:20},{n:'Distressed / credit',v:15},{n:'Cash',v:30}],
   suit:'Capital-preservation investors who value patience and dry powder.',
   avoid:'Investors uncomfortable holding large cash for long periods.',
   tara:'The most capital-protective style in the library. If avoiding big losses matters more to you than maximum gains, this fits your discipline well.',
   src:'Baupost Group 13F filings, SEC EDGAR; principles set out in Klarman\'s Margin of Safety.'}),
 L({id:'simons',name:'Jim Simons',style:'Quant Systematic',cat:'tradfi',initials:'JS',c1:'#7C6CFF',c2:'#6D28D9',
   ret3y:14.5,maxDD:-15,vol:12,consistency:92,riskAdj:1.1,risk:'Moderate',hold:'Days-months',horizon:'5+ years',
   bio:'Mathematician and founder of Renaissance Technologies, whose Medallion fund posted the best long-run record on record.',
   philosophy:'Let data and models, not narratives, drive thousands of small statistical bets with strict risk control.',
   hist:'Purely quantitative and largely undisclosed. Retail cannot truly replicate Medallion; this is an illustrative factor-diversified proxy.',
   sectors:['Systematic / Multi-factor'],
   alloc:[{k:'Multi-factor Equity',v:70},{k:'Trend / Managed futures',v:20},{k:'Cash',v:10}],
   holdings:[{n:'Multi-factor equity ETF',v:45},{n:'Momentum factor',v:15},{n:'Managed futures / trend',v:20},{n:'Value factor',v:10},{n:'Cash',v:10}],
   suit:'Investors curious about systematic factor investing as a diversifier.',
   avoid:'Anyone expecting to replicate Medallion\'s returns, which are closed and secret.',
   tara:'Important caveat: Medallion is closed and its methods secret, so this is a factor-based proxy, not the real thing. Treat any advertised quant returns with scepticism.',
   src:'Renaissance Technologies (Medallion returns widely reported but methods undisclosed). Proxy uses public multi-factor and managed-futures indices.'}),
 L({id:'burry',name:'Michael Burry',style:'Contrarian Deep Value',cat:'tradfi',initials:'MB',c1:'#FF7A9A',c2:'#DB2777',
   ret3y:7.2,maxDD:-38,vol:26,consistency:52,riskAdj:0.42,risk:'Very High',hold:'6 months-2 years',horizon:'5+ years',
   bio:'Founder of Scion Asset Management, made famous by The Big Short for betting against the 2008 housing bubble.',
   philosophy:'Find deeply mispriced or overvalued situations others ignore, and take contrarian positions with conviction.',
   hist:'Highly contrarian, concentrated, uses hedges and put options. Big swings and frequent portfolio turnover.',
   sectors:['Value','Special situations','Hedges'],
   alloc:[{k:'Deep-value Equity',v:65},{k:'Hedges / Puts',v:15},{k:'Cash',v:20}],
   holdings:[{n:'Deep-value equity basket',v:45},{n:'Contrarian sector bets',v:20},{n:'Index hedges / puts',v:15},{n:'Cash',v:20}],
   suit:'Experienced contrarians who understand hedging and can tolerate big swings.',
   avoid:'Long-term buy-and-hold investors and anyone new to investing.',
   tara:'A very low match for your DNA. Contrarian trading needs timing and nerve. Educational to study, but not a core you should build on.',
   src:'Scion Asset Management 13F filings, SEC EDGAR (note: 13F omits short and options positions).'}),
 L({id:'ackman',name:'Bill Ackman',style:'Activist Concentrated',cat:'tradfi',initials:'BA',c1:'#38BDF8',c2:'#0369A1',
   ret3y:13.9,maxDD:-30,vol:19,consistency:68,riskAdj:0.8,risk:'High',hold:'3-6 years',horizon:'5+ years',
   bio:'Founder of Pershing Square, a concentrated activist investor who takes large stakes in a few high-quality companies.',
   philosophy:'Own a handful of simple, predictable, cash-generative businesses and actively push for value creation.',
   hist:'Very concentrated (often under a dozen names), high conviction, uses occasional macro hedges. Lumpy returns.',
   sectors:['Consumer','Restaurants','Real estate','Financials'],
   alloc:[{k:'US Large-cap Equity',v:92},{k:'Cash / Hedges',v:8}],
   holdings:[{n:'Chipotle',v:18},{n:'Hilton',v:16},{n:'Restaurant Brands',v:14},{n:'Howard Hughes',v:12},{n:'Google',v:14},{n:'Others',v:18},{n:'Cash',v:8}],
   suit:'Investors who want a concentrated, quality activist tilt and can hold through swings.',
   avoid:'Those needing broad diversification or stable returns.',
   tara:'Quality names but very concentrated. As a satellite it adds conviction; as a core it would sharply cut your diversification score.',
   src:'Pershing Square Holdings 13F filings and semi-annual reports, SEC EDGAR.'}),
 L({id:'smith',name:'Terry Smith',style:'Quality Growth Compounders',cat:'tradfi',initials:'TS',c1:'#00C389',c2:'#00A878',
   ret3y:11.3,maxDD:-22,vol:14,consistency:87,riskAdj:0.9,risk:'Moderate',hold:'10+ years',horizon:'7+ years',
   bio:'Founder of Fundsmith, whose mantra is buy good companies, do not overpay, and do nothing.',
   philosophy:'Own a concentrated set of highly cash-generative global compounders with high returns on capital, and hold for the long run.',
   hist:'Low turnover, quality bias toward consumer staples, tech and healthcare. Lags in deep-value rallies.',
   sectors:['Consumer Staples','Technology','Healthcare'],
   alloc:[{k:'Global Quality Equity',v:96},{k:'Cash',v:4}],
   holdings:[{n:'Microsoft',v:9},{n:'Meta',v:8},{n:'Novo Nordisk',v:7},{n:'Philip Morris',v:6},{n:'L\'Oreal',v:6},{n:'Quality compounder basket',v:60},{n:'Cash',v:4}],
   suit:'Long-term investors who want global quality without frequent trading.',
   avoid:'Value investors or those who dislike concentration in expensive quality.',
   tara:'A high-quality global tilt that complements your US-heavy mix with more international consumer names. Well matched to your long horizon.',
   src:'Fundsmith Equity Fund monthly factsheets and annual letters at fundsmith.co.uk.'}),
 L({id:'browne',name:'Harry Browne',style:'Permanent Portfolio',cat:'tradfi',initials:'HB',c1:'#607D8B',c2:'#37474F',
   ret3y:5.9,maxDD:-14,vol:8,consistency:88,riskAdj:0.68,risk:'Low',hold:'Perpetual',horizon:'5+ years',
   bio:'Author and investment writer who designed the Permanent Portfolio to survive any economic condition with minimal maintenance.',
   philosophy:'Split equally across four assets that each shine in a different economic climate, then rebalance once a year and forget it.',
   hist:'Very low volatility and shallow drawdowns thanks to gold and long bonds. Modest long-run returns, extremely resilient.',
   sectors:['Multi-asset'],
   alloc:[{k:'US Equity',v:25},{k:'Long-term Bonds',v:25},{k:'Gold',v:25},{k:'Cash / T-bills',v:25}],
   holdings:[{n:'Total US Stock',v:25},{n:'Long-term Treasuries',v:25},{n:'Gold',v:25},{n:'T-bills / Money market',v:25}],
   suit:'Very cautious investors who want stability and simplicity above growth.',
   avoid:'Growth-focused investors who will not accept modest returns.',
   tara:'The calmest style in the library. If protecting capital and sleeping well matter most, this beats your current mix on drawdown, at the cost of some growth.',
   src:'Harry Browne\'s Fail-Safe Investing; the classic 25/25/25/25 Permanent Portfolio allocation.'})
];

/* ============================================================
   MARKET LEGENDS - 20 Crypto "Inspired By" model styles
   ============================================================ */
const CRYPTO = [
 L({id:'saylor',name:'Bitcoin Treasury',by:'Inspired by Michael Saylor / Strategy',cat:'crypto',initials:'₿',c1:'#F7931A',c2:'#B8690A',
   ret3y:41,maxDD:-77,vol:68,consistency:44,riskAdj:0.6,risk:'Very High',hold:'10+ years',horizon:'7+ years',
   bio:'Modelled on Strategy (formerly MicroStrategy) and Michael Saylor\'s corporate approach of holding Bitcoin as a primary treasury reserve asset.',
   philosophy:'Treat Bitcoin as long-term digital capital and hold with extreme conviction through deep drawdowns.',
   hist:'BTC-dominant, extremely volatile, subject to 70%+ drawdowns. High conviction, low activity.',
   sectors:['Bitcoin'],
   alloc:[{k:'Bitcoin',v:92},{k:'Cash / Stable',v:8}],
   holdings:[{n:'Bitcoin (BTC)',v:92},{n:'Stablecoin reserve',v:8}],
   suit:'Long-horizon believers in Bitcoin who can hold through brutal drawdowns.',
   avoid:'Anyone who needs stability, income, or the money within a few years.',
   tara:'Extremely volatile and concentrated in a single asset. This far exceeds the 10% crypto you hold today. If you follow it, size it as a small satellite, never a core.',
   src:'Strategy (MicroStrategy) SEC filings and public BTC purchase disclosures; holdings tracked publicly via saylortracker and company 8-Ks.'}),
 L({id:'eth-eco',name:'Ethereum Ecosystem',by:'Inspired by the Ethereum community',cat:'crypto',initials:'Ξ',c1:'#627EEA',c2:'#3C5BD6',
   ret3y:28,maxDD:-79,vol:72,consistency:40,riskAdj:0.45,risk:'Very High',hold:'5-7 years',horizon:'7+ years',
   bio:'Built around Ether and the smart-contract economy: staking, layer-2 scaling and on-chain applications.',
   philosophy:'Own the settlement layer of Web3 and earn staking yield while the ecosystem compounds.',
   hist:'ETH-led with staking income, high volatility, sensitive to network upgrades and DeFi cycles.',
   sectors:['Smart contracts','Layer-2','Staking'],
   alloc:[{k:'Ethereum',v:65},{k:'Layer-2 tokens',v:20},{k:'Staking / LSTs',v:10},{k:'Stable',v:5}],
   holdings:[{n:'Ethereum (ETH)',v:55},{n:'Staked ETH (LSTs)',v:15},{n:'Arbitrum / Optimism',v:15},{n:'Other L2 / infra',v:10},{n:'Stablecoin',v:5}],
   suit:'Investors bullish on smart contracts who want staking yield with high risk.',
   avoid:'Conservative investors and those who cannot hold through deep crypto winters.',
   tara:'Staking adds yield but does not offset the volatility. A thematic satellite at most for your profile.',
   src:'Ethereum Foundation resources at ethereum.org; on-chain staking data via beaconcha.in and L2 metrics on L2Beat.'}),
 L({id:'a16z',name:'Web3 Venture',by:'Inspired by a16z crypto theses',cat:'crypto',initials:'W3',c1:'#7C6CFF',c2:'#5B21B6',
   ret3y:18,maxDD:-85,vol:88,consistency:30,riskAdj:0.25,risk:'Extreme',hold:'5-8 years',horizon:'7+ years',
   bio:'A higher-risk basket of blockchain infrastructure themes inspired by venture theses from firms such as a16z crypto.',
   philosophy:'Back the picks-and-shovels of Web3 early: infrastructure, developer platforms and emerging protocols.',
   hist:'Small-cap heavy, illiquid, extreme drawdowns and dispersion. Many tokens go to zero, a few compound enormously.',
   sectors:['Infrastructure','DeFi','Developer platforms'],
   alloc:[{k:'Large-cap infra (ETH/SOL)',v:40},{k:'Mid-cap protocols',v:35},{k:'Emerging tokens',v:20},{k:'Stable',v:5}],
   holdings:[{n:'Ethereum / Solana',v:40},{n:'DeFi blue-chips',v:20},{n:'Infrastructure basket',v:20},{n:'Emerging protocols',v:15},{n:'Stable',v:5}],
   suit:'Risk-seeking investors treating this as venture-style money they can afford to lose.',
   avoid:'Everyone who needs the capital or cannot tolerate near-total loss on positions.',
   tara:'The highest-risk style in the whole library. Treat it as venture capital: tiny position, long horizon, expect several holdings to fail.',
   src:'a16z crypto published theses and State of Crypto reports at a16zcrypto.com; token data via CoinGecko.'}),
 L({id:'bluechip',name:'Crypto Blue-Chip Index',by:'Inspired by broad crypto index approaches',cat:'crypto',initials:'10',c1:'#4FC3F7',c2:'#0891B2',
   ret3y:32,maxDD:-74,vol:64,consistency:48,riskAdj:0.62,risk:'Very High',hold:'5+ years',horizon:'5+ years',
   bio:'A market-cap weighted basket of the largest, most established crypto assets, similar to a top-10 crypto index.',
   philosophy:'Own the crypto market rather than pick winners, weighting toward the largest and most liquid assets.',
   hist:'BTC and ETH dominated, still very volatile but less than single altcoins. Rebalanced periodically.',
   sectors:['Large-cap crypto'],
   alloc:[{k:'Bitcoin',v:55},{k:'Ethereum',v:25},{k:'Large-cap alts',v:15},{k:'Stable',v:5}],
   holdings:[{n:'Bitcoin',v:55},{n:'Ethereum',v:25},{n:'Solana',v:6},{n:'XRP / BNB',v:5},{n:'Other top-10',v:4},{n:'Stable',v:5}],
   suit:'Investors who want diversified crypto exposure without picking individual tokens.',
   avoid:'Anyone who cannot tolerate crypto-level volatility at all.',
   tara:'The most sensible way to hold crypto for most people: diversified and BTC/ETH weighted. Still volatile, so keep it within your crypto sleeve.',
   src:'Methodologies of broad crypto indices such as the Bitwise 10 and CoinDesk Market Index; constituent data on CoinGecko.'}),
 L({id:'btc-max',name:'BTC Maximalist',by:'Inspired by Bitcoin-only advocates',cat:'crypto',initials:'B!',c1:'#F7931A',c2:'#C2410C',
   ret3y:40,maxDD:-77,vol:66,consistency:46,riskAdj:0.62,risk:'Very High',hold:'10+ years',horizon:'7+ years',
   bio:'A Bitcoin-only philosophy that views BTC as uniquely sound digital money and avoids all other tokens.',
   philosophy:'One asset, maximum conviction: accumulate Bitcoin steadily and ignore the rest of the market.',
   hist:'Pure BTC, no altcoin risk but full single-asset concentration. Deep, prolonged drawdowns.',
   sectors:['Bitcoin'],
   alloc:[{k:'Bitcoin',v:97},{k:'Cash',v:3}],
   holdings:[{n:'Bitcoin (BTC)',v:97},{n:'Cash buffer',v:3}],
   suit:'Committed Bitcoiners who dollar-cost average and hold for the very long run.',
   avoid:'Investors who want diversification or altcoin upside.',
   tara:'All eggs in one basket, by design. Simpler than altcoin styles but no diversification. A small, regular accumulation fits a believer better than a lump sum.',
   src:'Public Bitcoin-only educational resources; BTC price and network data via mempool.space and Glassnode.'}),
 L({id:'macro-crypto',name:'Crypto Macro',by:'Inspired by Raoul Pal',cat:'crypto',initials:'RP',c1:'#38BDF8',c2:'#0284C7',
   ret3y:26,maxDD:-72,vol:60,consistency:50,riskAdj:0.55,risk:'Very High',hold:'3-5 years',horizon:'5+ years',
   bio:'A macro-driven crypto allocation inspired by Raoul Pal\'s view of crypto as the fastest-adopting technology in history.',
   philosophy:'Ride the long adoption curve of digital assets, tilting between BTC, ETH and liquidity-sensitive plays with the macro cycle.',
   hist:'Cycle-aware, BTC/ETH core with tactical tilts. Still highly volatile and liquidity-sensitive.',
   sectors:['Large-cap crypto','Macro'],
   alloc:[{k:'Bitcoin',v:45},{k:'Ethereum',v:30},{k:'Solana / L1s',v:15},{k:'Stable',v:10}],
   holdings:[{n:'Bitcoin',v:45},{n:'Ethereum',v:30},{n:'Solana',v:10},{n:'Other L1s',v:5},{n:'Stablecoin (dry powder)',v:10}],
   suit:'Investors who follow macro cycles and want an active crypto core.',
   avoid:'Passive investors and those uncomfortable with liquidity-driven swings.',
   tara:'Keeps some stablecoin dry powder, which suits your discipline. Still a high-risk sleeve, so cap the size.',
   src:'Raoul Pal / Global Macro Investor and Real Vision published research; asset data via CoinGecko.'}),
 L({id:'onchain-btc',name:'On-Chain BTC',by:'Inspired by Willy Woo',cat:'crypto',initials:'⛓',c1:'#F7931A',c2:'#9A3412',
   ret3y:38,maxDD:-75,vol:63,consistency:47,riskAdj:0.6,risk:'Very High',hold:'4-6 years',horizon:'5+ years',
   bio:'A Bitcoin strategy guided by on-chain analytics, inspired by analyst Willy Woo, that leans on network data to size exposure.',
   philosophy:'Use on-chain signals such as holder behaviour and network value to accumulate BTC through cycles.',
   hist:'BTC-centric with a small tactical stable buffer. Data-informed but still fully exposed to Bitcoin volatility.',
   sectors:['Bitcoin','On-chain analytics'],
   alloc:[{k:'Bitcoin',v:85},{k:'Stable (tactical)',v:15}],
   holdings:[{n:'Bitcoin',v:85},{n:'Stablecoin (tactical buffer)',v:15}],
   suit:'Data-driven Bitcoin investors comfortable with signal-based sizing.',
   avoid:'Investors who want a hands-off approach or diversification.',
   tara:'On-chain signals inform sizing but do not remove risk. Still a single-asset bet, so keep it modest within your plan.',
   src:'Willy Woo\'s on-chain research and Woobull charts; underlying data from Glassnode and Coin Metrics.'}),
 L({id:'s2f',name:'Stock-to-Flow BTC',by:'Inspired by PlanB (educational, model criticised)',cat:'crypto',initials:'S2F',c1:'#94A3B8',c2:'#475569',
   ret3y:35,maxDD:-80,vol:70,consistency:38,riskAdj:0.42,risk:'Extreme',hold:'4+ years',horizon:'5+ years',
   bio:'A Bitcoin accumulation style built around the Stock-to-Flow scarcity model popularised by the pseudonymous analyst PlanB.',
   philosophy:'Treat Bitcoin\'s programmed scarcity and halvings as the core thesis for long-term accumulation.',
   hist:'Halving-cycle oriented and BTC-only. Note: the Stock-to-Flow model has been widely criticised and has diverged from price.',
   sectors:['Bitcoin'],
   alloc:[{k:'Bitcoin',v:90},{k:'Stable',v:10}],
   holdings:[{n:'Bitcoin',v:90},{n:'Stablecoin',v:10}],
   suit:'Investors interested in scarcity-based accumulation who understand the model\'s limits.',
   avoid:'Anyone treating any price model as a guarantee.',
   tara:'Important caveat: the Stock-to-Flow model has been repeatedly wrong and should never be read as a forecast. Included for education, not as a target.',
   src:'PlanB\'s Stock-to-Flow articles (2019 onward); note widespread academic and market criticism of the model\'s predictive power.'}),
 L({id:'galaxy',name:'Institutional Diversified',by:'Inspired by Galaxy / Novogratz',cat:'crypto',initials:'GX',c1:'#7C6CFF',c2:'#4338CA',
   ret3y:29,maxDD:-71,vol:58,consistency:52,riskAdj:0.58,risk:'High',hold:'4-6 years',horizon:'5+ years',
   bio:'An institution-style diversified crypto allocation inspired by Mike Novogratz\'s Galaxy Digital, blending core assets with infrastructure.',
   philosophy:'Hold a professionally diversified crypto book: majors, staking, and select infrastructure with risk controls.',
   hist:'Diversified across majors and infra with a stable buffer. Lower volatility than single-token bets, still high risk.',
   sectors:['Large-cap crypto','Infrastructure','Staking'],
   alloc:[{k:'Bitcoin',v:40},{k:'Ethereum',v:25},{k:'Infrastructure',v:20},{k:'Staking',v:5},{k:'Stable',v:10}],
   holdings:[{n:'Bitcoin',v:40},{n:'Ethereum',v:25},{n:'Infra / L1 basket',v:20},{n:'Staking positions',v:5},{n:'Stablecoin',v:10}],
   suit:'Investors who want a professionally diversified crypto sleeve rather than a single bet.',
   avoid:'Those who cannot accept crypto volatility even when diversified.',
   tara:'One of the more balanced crypto styles, with a stable buffer and diversification. A reasonable shape if you decide to grow your crypto sleeve.',
   src:'Galaxy Digital research and public commentary from Mike Novogratz; asset data via CoinGecko.'}),
 L({id:'defi-yield',name:'DeFi Yield',by:'Inspired by Andre Cronje / Yearn',cat:'crypto',initials:'%',c1:'#34D399',c2:'#047857',
   ret3y:14,maxDD:-82,vol:76,consistency:34,riskAdj:0.3,risk:'Extreme',hold:'2-4 years',horizon:'5+ years',
   bio:'A yield-focused DeFi strategy inspired by Andre Cronje\'s Yearn, seeking on-chain income from lending and liquidity.',
   philosophy:'Put crypto capital to work in decentralised protocols to earn yield, accepting smart-contract and de-peg risk.',
   hist:'Income-oriented but exposed to smart-contract exploits, de-pegs and impermanent loss. Yields are variable, not guaranteed.',
   sectors:['DeFi','Lending','Liquidity'],
   alloc:[{k:'Stablecoin yield',v:45},{k:'ETH staking',v:25},{k:'DeFi blue-chips',v:20},{k:'BTC',v:10}],
   holdings:[{n:'Stablecoin lending / vaults',v:45},{n:'Staked ETH',v:25},{n:'DeFi governance tokens',v:20},{n:'Bitcoin',v:10}],
   suit:'Technical investors who understand smart-contract and protocol risk.',
   avoid:'Beginners, and anyone who assumes advertised yields are safe or fixed.',
   tara:'DeFi yields look attractive but carry real risk of protocol hacks and stablecoin de-pegs. High advertised APYs are compensation for that risk, not free money.',
   src:'Yearn Finance and DeFi protocol documentation; yield and TVL data via DeFiLlama. Yields are variable and not guaranteed.'}),
 L({id:'bnb',name:'Exchange Ecosystem',by:'Inspired by exchange-token models',cat:'crypto',initials:'EX',c1:'#F3BA2F',c2:'#B8860B',
   ret3y:24,maxDD:-73,vol:62,consistency:45,riskAdj:0.5,risk:'Very High',hold:'3-5 years',horizon:'5+ years',
   bio:'A strategy centred on the utility tokens of major exchange ecosystems and their associated chains.',
   philosophy:'Own the tokens that power large trading and chain ecosystems, capturing fee and utility demand.',
   hist:'Concentrated in exchange-linked tokens, exposed to regulatory and platform-specific risk on top of market volatility.',
   sectors:['Exchange tokens','Layer-1'],
   alloc:[{k:'Exchange token',v:45},{k:'Bitcoin',v:25},{k:'Ethereum',v:20},{k:'Stable',v:10}],
   holdings:[{n:'Exchange utility token',v:45},{n:'Bitcoin',v:25},{n:'Ethereum',v:20},{n:'Stablecoin',v:10}],
   suit:'Investors bullish on a specific exchange ecosystem who accept platform risk.',
   avoid:'Those wary of concentration in a single company\'s token or regulatory risk.',
   tara:'Exchange tokens add company and regulatory risk on top of crypto volatility. More concentrated than a blue-chip index, so weigh that carefully.',
   src:'Public exchange tokenomics disclosures; market data via CoinGecko. Regulatory status of exchange tokens varies by jurisdiction.'}),
 L({id:'dex',name:'DeFi Blue-Chip',by:'Inspired by Uniswap / DEX leaders',cat:'crypto',initials:'🦄',c1:'#FF7A9A',c2:'#BE185D',
   ret3y:16,maxDD:-84,vol:80,consistency:33,riskAdj:0.3,risk:'Extreme',hold:'3-5 years',horizon:'5+ years',
   bio:'A basket of leading decentralised-finance protocol tokens such as decentralised exchanges and lending platforms.',
   philosophy:'Own the governance tokens of the most-used DeFi applications as a bet on decentralised financial infrastructure.',
   hist:'High beta to the crypto cycle, deep drawdowns, governance and dilution risk. Liquidity varies widely.',
   sectors:['DeFi','DEX','Lending'],
   alloc:[{k:'ETH',v:35},{k:'DEX tokens',v:30},{k:'Lending tokens',v:25},{k:'Stable',v:10}],
   holdings:[{n:'Ethereum',v:35},{n:'DEX governance tokens',v:30},{n:'Lending protocol tokens',v:25},{n:'Stablecoin',v:10}],
   suit:'DeFi believers who accept governance-token and dilution risk.',
   avoid:'Conservative investors and those who need liquidity certainty.',
   tara:'A high-beta bet on DeFi adoption. Governance tokens can dilute and swing hard. Keep this to a small, speculative slice.',
   src:'Protocol documentation for leading DEX and lending platforms; token and TVL data via DeFiLlama and CoinGecko.'}),
 L({id:'regulated',name:'Regulated Crypto',by:'Inspired by Gemini / Winklevoss approach',cat:'crypto',initials:'✓',c1:'#4FC3F7',c2:'#1D4ED8',
   ret3y:30,maxDD:-72,vol:59,consistency:50,riskAdj:0.58,risk:'High',hold:'5+ years',horizon:'5+ years',
   bio:'A compliance-first crypto allocation inspired by the Winklevoss twins\' Gemini, favouring regulated custody and blue-chip assets.',
   philosophy:'Prioritise regulated venues, insured custody and the most established assets to reduce operational risk.',
   hist:'BTC/ETH heavy with an emphasis on custody safety. Market risk remains high even if operational risk is lower.',
   sectors:['Large-cap crypto'],
   alloc:[{k:'Bitcoin',v:55},{k:'Ethereum',v:30},{k:'Stable (regulated)',v:15}],
   holdings:[{n:'Bitcoin (regulated custody)',v:55},{n:'Ethereum',v:30},{n:'Regulated stablecoin',v:15}],
   suit:'Cautious crypto investors who prioritise custody safety and compliance.',
   avoid:'Investors seeking altcoin upside or maximum returns.',
   tara:'Reducing operational and custody risk is smart, but it does not reduce Bitcoin\'s price swings. Still a high-risk sleeve, just a safer wrapper.',
   src:'Public disclosures from regulated exchanges such as Gemini; custody and insurance terms vary by provider.'}),
 L({id:'network-state',name:'Network State BTC',by:'Inspired by Balaji Srinivasan',cat:'crypto',initials:'NS',c1:'#7C6CFF',c2:'#6D28D9',
   ret3y:37,maxDD:-78,vol:67,consistency:42,riskAdj:0.55,risk:'Very High',hold:'7+ years',horizon:'10+ years',
   bio:'A long-horizon thesis inspired by Balaji Srinivasan, holding Bitcoin as the reserve asset of an internet-native future.',
   philosophy:'Hold hard digital money for a decade-plus as a hedge against monetary debasement and a bet on decentralisation.',
   hist:'BTC-dominant with a gold sleeve as a fellow hard asset. Very long horizon, very high volatility.',
   sectors:['Bitcoin','Hard assets'],
   alloc:[{k:'Bitcoin',v:80},{k:'Gold',v:12},{k:'Stable',v:8}],
   holdings:[{n:'Bitcoin',v:80},{n:'Gold',v:12},{n:'Stablecoin',v:8}],
   suit:'Very long-horizon investors hedging against monetary debasement.',
   avoid:'Anyone with a short horizon or low risk tolerance.',
   tara:'A decade-plus thesis, not a trade. Pairs Bitcoin with gold as hard assets. Only sensible with money you will not touch for many years.',
   src:'Balaji Srinivasan\'s The Network State and public essays; BTC and gold data via public market sources.'}),
 L({id:'l1-div',name:'Layer-1 Diversified',by:'Inspired by multi-chain investors',cat:'crypto',initials:'L1',c1:'#38BDF8',c2:'#0E7490',
   ret3y:20,maxDD:-83,vol:78,consistency:36,riskAdj:0.32,risk:'Extreme',hold:'3-5 years',horizon:'5+ years',
   bio:'A basket spread across competing layer-1 smart-contract blockchains rather than betting on a single winner.',
   philosophy:'Diversify across the leading base-layer chains to capture whichever platform wins developer and user adoption.',
   hist:'High dispersion between chains, extreme volatility, technology and security risk varies by network.',
   sectors:['Layer-1'],
   alloc:[{k:'Ethereum',v:35},{k:'Solana',v:20},{k:'Other L1s',v:35},{k:'Stable',v:10}],
   holdings:[{n:'Ethereum',v:35},{n:'Solana',v:20},{n:'Avalanche / others',v:20},{n:'Emerging L1s',v:15},{n:'Stable',v:10}],
   suit:'Investors who want smart-contract exposure without picking one chain.',
   avoid:'Risk-averse investors and those who dislike high token dispersion.',
   tara:'Spreading across chains reduces single-network risk but not market risk. Several of these tokens could still fail, so keep the slice small.',
   src:'Public chain metrics via DefiLlama and Token Terminal; token data via CoinGecko.'}),
 L({id:'crypto-cons',name:'Crypto Conservative',by:'BTC + stable income model',cat:'crypto',initials:'C-',c1:'#00C389',c2:'#047857',
   ret3y:16,maxDD:-42,vol:34,consistency:62,riskAdj:0.6,risk:'High',hold:'3-5 years',horizon:'5+ years',
   bio:'The most cautious way to hold crypto: a core Bitcoin position paired with a large stablecoin income sleeve.',
   philosophy:'Keep crypto exposure meaningful but bounded, using stablecoins to cut volatility and generate yield.',
   hist:'Much lower drawdown than pure crypto thanks to the stable sleeve. Still riskier than traditional assets.',
   sectors:['Bitcoin','Stablecoins'],
   alloc:[{k:'Bitcoin',v:40},{k:'Stablecoin income',v:50},{k:'Ethereum',v:10}],
   holdings:[{n:'Bitcoin',v:40},{n:'Stablecoin (yield)',v:50},{n:'Ethereum',v:10}],
   suit:'Cautious investors dipping into crypto who want a softer ride.',
   avoid:'Investors chasing maximum crypto upside.',
   tara:'The best-matched crypto style for a Balanced Builder. Half in stablecoins cuts the volatility hard. If you grow your crypto sleeve, shape it like this.',
   src:'Illustrative model; stablecoin yields sourced from regulated lending and tokenised T-bill products (variable, not guaranteed).'}),
 L({id:'crypto-bal',name:'Crypto Balanced',by:'BTC core + ETH growth model',cat:'crypto',initials:'C=',c1:'#4FC3F7',c2:'#2563EB',
   ret3y:27,maxDD:-70,vol:57,consistency:52,riskAdj:0.56,risk:'High',hold:'4-6 years',horizon:'5+ years',
   bio:'A balanced crypto allocation with a Bitcoin core, Ethereum for growth and a small infrastructure sleeve.',
   philosophy:'Anchor in Bitcoin, add Ethereum for smart-contract growth, and keep a small infra allocation for optionality.',
   hist:'Diversified within crypto, still highly volatile but less than single-token styles. Periodic rebalancing.',
   sectors:['Large-cap crypto','Infrastructure'],
   alloc:[{k:'Bitcoin',v:50},{k:'Ethereum',v:30},{k:'Infrastructure',v:12},{k:'Stable',v:8}],
   holdings:[{n:'Bitcoin',v:50},{n:'Ethereum',v:30},{n:'Infra tokens',v:12},{n:'Stablecoin',v:8}],
   suit:'Investors who want a diversified but growth-tilted crypto sleeve.',
   avoid:'Conservative investors who cannot hold through 60%+ drops.',
   tara:'A sensible middle ground within crypto. More growth tilt than Crypto Conservative, more diversified than a single-token bet.',
   src:'Illustrative model built from BTC, ETH and large-cap infrastructure tokens; data via CoinGecko.'}),
 L({id:'stable-income',name:'Stablecoin Income',by:'Tokenised cash & T-bill yield',cat:'crypto',initials:'$',c1:'#34D399',c2:'#059669',
   ret3y:5.2,maxDD:-4,vol:3,consistency:78,riskAdj:0.9,risk:'Moderate',hold:'1-3 years',horizon:'2+ years',
   bio:'A low-volatility digital-cash strategy earning yield from regulated stablecoins and tokenised treasury products.',
   philosophy:'Use blockchain rails for cash-like yield, prioritising regulated issuers and short-duration collateral.',
   hist:'Very low volatility if issuers hold. Main risks are de-peg and counterparty, not market swings.',
   sectors:['Stablecoins','Tokenised T-bills'],
   alloc:[{k:'Regulated stablecoins',v:60},{k:'Tokenised T-bills',v:35},{k:'BTC (tiny)',v:5}],
   holdings:[{n:'Regulated stablecoin yield',v:60},{n:'Tokenised T-bill fund',v:35},{n:'Bitcoin (satellite)',v:5}],
   suit:'Investors wanting cash-like yield on-chain with minimal price swings.',
   avoid:'Anyone assuming stablecoins are risk-free; de-peg risk is real.',
   tara:'The calmest crypto-adjacent style, closer to digital cash than an investment. Watch issuer and de-peg risk. Could replace some of your idle cash.',
   src:'Regulated stablecoin attestations and tokenised T-bill products (e.g. money-market tokens); yields variable and not guaranteed.'}),
 L({id:'staking',name:'Staking Income',by:'ETH staking & LST model',cat:'crypto',initials:'⧉',c1:'#627EEA',c2:'#4338CA',
   ret3y:18,maxDD:-76,vol:64,consistency:48,riskAdj:0.48,risk:'Very High',hold:'4-6 years',horizon:'5+ years',
   bio:'A yield strategy that stakes proof-of-stake assets, chiefly Ethereum, to earn native rewards while holding the asset.',
   philosophy:'Earn protocol-level staking rewards on assets you hold long term, compounding yield on top of price exposure.',
   hist:'Staking yield partly cushions returns but not price risk. Liquid staking tokens add smart-contract risk.',
   sectors:['Staking','Layer-1'],
   alloc:[{k:'Staked ETH / LSTs',v:60},{k:'Other staked L1s',v:20},{k:'Bitcoin',v:15},{k:'Stable',v:5}],
   holdings:[{n:'Staked ETH (LSTs)',v:60},{n:'Staked L1s',v:20},{n:'Bitcoin',v:15},{n:'Stable',v:5}],
   suit:'Long-term PoS holders who want native yield on their positions.',
   avoid:'Investors who need liquidity or dislike smart-contract risk from LSTs.',
   tara:'Staking yield is real but does not offset the underlying volatility, and liquid staking adds contract risk. A yield tilt on a high-risk base.',
   src:'Ethereum staking data via beaconcha.in; liquid staking metrics via DeFiLlama. Rewards vary with network participation.'}),
 L({id:'gamefi',name:'GameFi & Metaverse',by:'Higher-risk thematic basket',cat:'crypto',initials:'🎮',c1:'#FF7A9A',c2:'#9D174D',
   ret3y:8,maxDD:-90,vol:95,consistency:22,riskAdj:0.18,risk:'Extreme',hold:'3-5 years',horizon:'7+ years',
   bio:'A speculative thematic basket of gaming, metaverse and NFT-linked tokens at the frontier of consumer crypto.',
   philosophy:'Bet on crypto reaching mainstream consumers through games and virtual worlds, accepting extreme dispersion.',
   hist:'The most speculative theme in crypto: 90%+ drawdowns common, many projects fail, occasional huge winners.',
   sectors:['Gaming','Metaverse','NFT infrastructure'],
   alloc:[{k:'Gaming tokens',v:40},{k:'Metaverse tokens',v:30},{k:'ETH / infra',v:20},{k:'Stable',v:10}],
   holdings:[{n:'Gaming platform tokens',v:40},{n:'Metaverse land / tokens',v:30},{n:'Ethereum / infra',v:20},{n:'Stable',v:10}],
   suit:'Speculators using money they can fully afford to lose.',
   avoid:'Almost everyone as anything more than a tiny punt.',
   tara:'The riskiest thematic in the library, with 90% drawdowns on record. This is a lottery ticket, not an investment. Size accordingly, if at all.',
   src:'Sector token data via CoinGecko GameFi and Metaverse categories; extreme historical drawdowns are well documented.'})
];

/* ============================================================
   COMMUNITY INVESTORS - anonymised, illustrative Vault22 users
   Ranked by risk-adjusted performance, not raw return.
   Consent + anonymisation assumed; no real PII.
   ============================================================ */
function C(o){ o.community=true; return o; }
const COMMUNITY = [
 C({id:'c1',name:'Investor #4821',initials:'48',c1:'#00C389',c2:'#009E70',style:'Balanced Growth',cat:'Balanced',
   match:91,badge:'Elite Consistency',riskAdj:1.12,maxDD:-16,vol:11,behaviour:94,divers:88,years:9,shariah:false,overlap:74,riskLbl:'Moderate',ret3y:11.8,ret1y:14.2,ret30:1.1,ret90:3.2,consistency:90,followers:2140,watchers:610,
   alloc:[{k:'Global Equity',v:52},{k:'Bonds',v:20},{k:'Crypto',v:8},{k:'REITs',v:10},{k:'Cash',v:10}],
   sectors:[{k:'Technology',v:28},{k:'Financials',v:18},{k:'Healthcare',v:14},{k:'Consumer',v:16},{k:'Industrials',v:12},{k:'Other',v:12}],
   geo:[{k:'North America',v:52},{k:'Europe',v:20},{k:'Asia-Pacific',v:16},{k:'Emerging',v:12}],
   mcap:[{k:'Mega',v:44},{k:'Large',v:30},{k:'Mid',v:18},{k:'Small',v:8}],
   holdings:[{n:'Global Equity ETF',v:34},{n:'US Total Market',v:18},{n:'Aggregate Bonds',v:20},{n:'REIT ETF',v:10},{n:'Bitcoin',v:8},{n:'Cash',v:10}],
   summary:'A textbook disciplined builder: diversified, rarely trades, contributes monthly and held firmly through the last correction. Very close to your own style, one notch more diversified.',
   philosophy:'Diversify globally, contribute every month, rebalance yearly, ignore the noise.',
   timeline:[['3y ago','Started with a global ETF core'],['2y ago','Added bond ballast and REITs'],['14m ago','Held through a 12% drawdown, kept contributing'],['4m ago','Trimmed tech, added emerging markets']],
   changes:[['Added Emerging Markets ETF','4 months ago'],['Rebalanced to target','7 months ago']],
   risk:{sharpe:1.12,vol:11,maxDD:-16,beta:0.86}}),
 C({id:'c2',name:'Investor #1177',initials:'11',c1:'#4FC3F7',c2:'#2196F3',style:'Global Index Core',cat:'Growth',
   match:87,badge:'Long-Term Investor',riskAdj:1.02,maxDD:-19,vol:13,behaviour:90,divers:82,years:12,shariah:false,overlap:69,riskLbl:'Moderate',ret3y:10.6,ret1y:12.9,ret30:0.8,ret90:2.7,consistency:93,followers:3320,watchers:880,
   alloc:[{k:'Global Equity',v:70},{k:'Bonds',v:22},{k:'Cash',v:8}],
   sectors:[{k:'Technology',v:26},{k:'Financials',v:16},{k:'Healthcare',v:13},{k:'Consumer',v:15},{k:'Industrials',v:14},{k:'Other',v:16}],
   geo:[{k:'North America',v:58},{k:'Europe',v:18},{k:'Asia-Pacific',v:14},{k:'Emerging',v:10}],
   mcap:[{k:'Mega',v:48},{k:'Large',v:30},{k:'Mid',v:14},{k:'Small',v:8}],
   holdings:[{n:'Total World Stock',v:50},{n:'US Total Market',v:20},{n:'Total Bond',v:22},{n:'Cash',v:8}],
   summary:'A pure Bogle-style indexer with 12 years of unbroken discipline. Lowest maintenance in the community. Slightly more equity risk than your current mix.',
   philosophy:'Own the whole market cheaply and never sell.',
   timeline:[['5y ago','Consolidated into three funds'],['3y ago','Automated monthly contributions'],['1y ago','Did nothing, by design']],
   changes:[['Annual rebalance','2 months ago']],
   risk:{sharpe:1.02,vol:13,maxDD:-19,beta:0.98}}),
 C({id:'c3',name:'Investor #9032',initials:'90',c1:'#00C389',c2:'#00E0A0',style:'Shariah Balanced',cat:'Balanced',
   match:84,badge:'Diversification Expert',riskAdj:0.98,maxDD:-17,vol:12,behaviour:92,divers:86,years:7,shariah:true,overlap:58,riskLbl:'Moderate',ret3y:9.9,ret1y:11.4,ret30:0.7,ret90:2.4,consistency:88,followers:1580,watchers:520,
   alloc:[{k:'Shariah Equity',v:64},{k:'Sukuk',v:24},{k:'Gold',v:6},{k:'Cash',v:6}],
   sectors:[{k:'Technology',v:30},{k:'Healthcare',v:18},{k:'Industrials',v:16},{k:'Materials',v:12},{k:'Consumer',v:14},{k:'Other',v:10}],
   geo:[{k:'North America',v:46},{k:'Europe',v:18},{k:'Asia-Pacific',v:22},{k:'Emerging',v:14}],
   mcap:[{k:'Mega',v:40},{k:'Large',v:32},{k:'Mid',v:20},{k:'Small',v:8}],
   holdings:[{n:'Shariah Global Equity',v:44},{n:'Shariah US Equity',v:20},{n:'Sukuk',v:24},{n:'Gold',v:6},{n:'Cash',v:6}],
   summary:'Fully Shariah-compliant and beautifully diversified. Naturally light on financials, strong in tech and healthcare. A great template if faith-based screening matters to you.',
   philosophy:'Grow within Shariah screens, balance equities with sukuk, stay patient.',
   timeline:[['4y ago','Built a Shariah equity core'],['2y ago','Added sukuk for stability'],['8m ago','Added a small gold sleeve']],
   changes:[['Added gold sleeve','8 months ago'],['Sukuk top-up','1 year ago']],
   risk:{sharpe:0.98,vol:12,maxDD:-17,beta:0.82}}),
 C({id:'c4',name:'Investor #6410',initials:'64',c1:'#7C6CFF',c2:'#5B47FB',style:'High-Conviction Growth',cat:'Growth',
   match:62,badge:'Risk Manager',riskAdj:0.79,maxDD:-34,vol:24,behaviour:74,divers:58,years:6,shariah:false,overlap:47,riskLbl:'High',ret3y:15.4,ret1y:22.1,ret30:2.0,ret90:4.9,consistency:64,followers:5210,watchers:1740,
   alloc:[{k:'Growth Equity',v:74},{k:'Crypto',v:14},{k:'Cash',v:12}],
   sectors:[{k:'Technology',v:46},{k:'Consumer',v:16},{k:'Healthcare',v:14},{k:'Communications',v:12},{k:'Other',v:12}],
   geo:[{k:'North America',v:74},{k:'Asia-Pacific',v:14},{k:'Europe',v:8},{k:'Emerging',v:4}],
   mcap:[{k:'Mega',v:56},{k:'Large',v:24},{k:'Mid',v:14},{k:'Small',v:6}],
   holdings:[{n:'Mega-cap tech basket',v:40},{n:'Growth equity',v:24},{n:'Bitcoin + ETH',v:14},{n:'Cash',v:12}],
   summary:'Strong returns but a bumpy ride, with a 34% drawdown on record. Keeps cash as a shock absorber, which lifts the behaviour score. Higher risk than your DNA suggests you want.',
   philosophy:'Concentrate in quality growth, keep dry powder, add on big dips.',
   timeline:[['3y ago','Concentrated into mega-cap tech'],['18m ago','Added a crypto sleeve'],['6m ago','Raised cash after a strong run']],
   changes:[['Raised cash to 12%','6 months ago'],['Added ETH','11 months ago']],
   risk:{sharpe:0.79,vol:24,maxDD:-34,beta:1.28}}),
 C({id:'c5',name:'Investor #2288',initials:'22',c1:'#E7C27D',c2:'#C9A24B',style:'Dividend Income',cat:'Income',
   match:78,badge:'Long-Term Investor',riskAdj:0.95,maxDD:-15,vol:10,behaviour:91,divers:80,years:14,shariah:false,overlap:55,riskLbl:'Low-Moderate',ret3y:8.4,ret1y:9.1,ret30:0.6,ret90:2.0,consistency:91,followers:2760,watchers:640,
   alloc:[{k:'Dividend Equity',v:66},{k:'Bonds',v:22},{k:'REITs',v:8},{k:'Cash',v:4}],
   sectors:[{k:'Consumer Staples',v:22},{k:'Financials',v:18},{k:'Utilities',v:14},{k:'Energy',v:12},{k:'Healthcare',v:16},{k:'Other',v:18}],
   geo:[{k:'North America',v:60},{k:'Europe',v:24},{k:'Asia-Pacific',v:12},{k:'Emerging',v:4}],
   mcap:[{k:'Mega',v:50},{k:'Large',v:34},{k:'Mid',v:12},{k:'Small',v:4}],
   holdings:[{n:'Dividend Aristocrats ETF',v:40},{n:'High-dividend equity',v:26},{n:'Bonds',v:22},{n:'REITs',v:8},{n:'Cash',v:4}],
   summary:'An income specialist with the shallowest drawdown in the community and 14 years of steady contributions. Lower growth than your mix, but far smoother.',
   philosophy:'Own quality dividend payers, reinvest income, prize stability.',
   timeline:[['7y ago','Shifted toward dividend payers'],['3y ago','Added REIT income'],['1y ago','Reinvested all dividends']],
   changes:[['REIT top-up','5 months ago']],
   risk:{sharpe:0.95,vol:10,maxDD:-15,beta:0.7}}),
 C({id:'c6',name:'Investor #7745',initials:'77',c1:'#34D399',c2:'#059669',style:'All-Weather Defensive',cat:'Balanced',
   match:81,badge:'Risk Manager',riskAdj:0.9,maxDD:-12,vol:8,behaviour:93,divers:90,years:10,shariah:false,overlap:52,riskLbl:'Low',ret3y:6.8,ret1y:7.4,ret30:0.4,ret90:1.5,consistency:93,followers:1910,watchers:480,
   alloc:[{k:'Equity',v:35},{k:'Long Bonds',v:35},{k:'Gold',v:15},{k:'Commodities',v:8},{k:'Cash',v:7}],
   sectors:[{k:'Broad',v:100}],
   geo:[{k:'North America',v:50},{k:'Europe',v:22},{k:'Asia-Pacific',v:18},{k:'Emerging',v:10}],
   mcap:[{k:'Mega',v:42},{k:'Large',v:34},{k:'Mid',v:16},{k:'Small',v:8}],
   holdings:[{n:'Total Stock',v:35},{n:'Long Treasuries',v:35},{n:'Gold',v:15},{n:'Commodities',v:8},{n:'Cash',v:7}],
   summary:'The steadiest hand in the community: a risk-parity build with a 12% worst drawdown and the highest diversification score. Gives up upside for a very smooth ride.',
   philosophy:'Balance risk across economic seasons, rebalance, never panic.',
   timeline:[['5y ago','Adopted an all-weather allocation'],['2y ago','Added a commodities sleeve'],['9m ago','Rebalanced after a bond rally']],
   changes:[['Rebalanced sleeves','3 months ago']],
   risk:{sharpe:0.9,vol:8,maxDD:-12,beta:0.42}}),
 C({id:'c7',name:'Investor #3390',initials:'33',c1:'#38BDF8',c2:'#0284C7',style:'Emerging Markets Tilt',cat:'Growth',
   match:59,badge:'Diversification Expert',riskAdj:0.72,maxDD:-31,vol:21,behaviour:80,divers:76,years:8,shariah:false,overlap:38,riskLbl:'High',ret3y:9.2,ret1y:16.8,ret30:-1.1,ret90:3.6,consistency:61,followers:1440,watchers:410,
   alloc:[{k:'Emerging Equity',v:52},{k:'Developed Equity',v:30},{k:'Bonds',v:10},{k:'Cash',v:8}],
   sectors:[{k:'Technology',v:30},{k:'Financials',v:22},{k:'Materials',v:14},{k:'Consumer',v:16},{k:'Energy',v:10},{k:'Other',v:8}],
   geo:[{k:'Emerging',v:52},{k:'Asia-Pacific',v:24},{k:'North America',v:16},{k:'Europe',v:8}],
   mcap:[{k:'Mega',v:34},{k:'Large',v:32},{k:'Mid',v:22},{k:'Small',v:12}],
   holdings:[{n:'Emerging Markets ETF',v:40},{n:'Asia ex-Japan',v:12},{n:'Developed Equity',v:30},{n:'EM Bonds',v:10},{n:'Cash',v:8}],
   summary:'A growth-seeking tilt toward emerging markets. Higher volatility and a 31% drawdown, but genuine diversification away from US mega-cap. Low overlap with you, so a bigger change to adopt.',
   philosophy:'Lean into faster-growing economies, accept volatility for long-run growth.',
   timeline:[['4y ago','Overweighted emerging markets'],['2y ago','Added Asia ex-Japan'],['5m ago','Trimmed after a strong rally']],
   changes:[['Trimmed EM winners','5 months ago']],
   risk:{sharpe:0.72,vol:21,maxDD:-31,beta:1.14}}),
 C({id:'c8',name:'Investor #5561',initials:'55',c1:'#00C389',c2:'#00A878',style:'Core + Crypto Satellite',cat:'Balanced',
   match:88,badge:'Elite Consistency',riskAdj:1.05,maxDD:-21,vol:14,behaviour:89,divers:84,years:7,shariah:false,overlap:71,riskLbl:'Moderate',ret3y:12.6,ret1y:17.3,ret30:1.4,ret90:3.9,consistency:87,followers:2980,watchers:960,
   alloc:[{k:'Global Equity',v:56},{k:'Bonds',v:18},{k:'Crypto',v:12},{k:'Cash',v:14}],
   sectors:[{k:'Technology',v:30},{k:'Financials',v:16},{k:'Healthcare',v:14},{k:'Consumer',v:16},{k:'Industrials',v:12},{k:'Other',v:12}],
   geo:[{k:'North America',v:56},{k:'Europe',v:18},{k:'Asia-Pacific',v:16},{k:'Emerging',v:10}],
   mcap:[{k:'Mega',v:46},{k:'Large',v:28},{k:'Mid',v:18},{k:'Small',v:8}],
   holdings:[{n:'Global Equity ETF',v:38},{n:'US Total Market',v:18},{n:'Aggregate Bonds',v:18},{n:'Bitcoin + ETH',v:12},{n:'Cash',v:14}],
   summary:'Almost a mirror of your portfolio with a slightly larger, well-managed crypto satellite. Highest overlap in the community, so the smallest change to adopt. Strong risk-adjusted record.',
   philosophy:'Index core, small crypto satellite, keep cash for opportunities.',
   timeline:[['3y ago','Built a global index core'],['2y ago','Added a capped crypto satellite'],['6m ago','Rebalanced crypto back to 12%']],
   changes:[['Rebalanced crypto to 12%','6 months ago'],['Added cash buffer','10 months ago']],
   risk:{sharpe:1.05,vol:14,maxDD:-21,beta:0.99}}),
 C({id:'c9',name:'Investor #8123',initials:'81',c1:'#FF7A9A',c2:'#DB2777',style:'Thematic Innovation',cat:'Growth',
   match:48,badge:'Risk Manager',riskAdj:0.55,maxDD:-52,vol:33,behaviour:66,divers:44,years:5,shariah:false,overlap:29,riskLbl:'Very High',ret3y:10.1,ret1y:29.4,ret30:-3.2,ret90:5.1,consistency:44,followers:6640,watchers:2210,
   alloc:[{k:'Innovation Equity',v:78},{k:'Crypto',v:14},{k:'Cash',v:8}],
   sectors:[{k:'Technology',v:52},{k:'Healthcare',v:16},{k:'Communications',v:14},{k:'Consumer',v:10},{k:'Other',v:8}],
   geo:[{k:'North America',v:80},{k:'Asia-Pacific',v:12},{k:'Europe',v:6},{k:'Emerging',v:2}],
   mcap:[{k:'Mega',v:38},{k:'Large',v:24},{k:'Mid',v:24},{k:'Small',v:14}],
   holdings:[{n:'Disruptive innovation basket',v:48},{n:'AI & robotics',v:18},{n:'Genomics',v:12},{n:'Crypto',v:14},{n:'Cash',v:8}],
   summary:'The highest raw returns lately, but with a 52% drawdown and low diversification. A cautionary example of why we rank on risk-adjusted performance, not returns. A poor match for your DNA.',
   philosophy:'Concentrate in disruptive innovation and hold through the swings.',
   timeline:[['3y ago','Went all-in on innovation themes'],['1y ago','Survived a 50% drawdown'],['4m ago','Added AI names on strength']],
   changes:[['Added AI basket','4 months ago']],
   risk:{sharpe:0.55,vol:33,maxDD:-52,beta:1.62}}),
 C({id:'c10',name:'Investor #4004',initials:'40',c1:'#90A4AE',c2:'#607D8B',style:'Capital Preservation',cat:'Income',
   match:70,badge:'Risk Manager',riskAdj:0.86,maxDD:-9,vol:6,behaviour:95,divers:78,years:16,shariah:false,overlap:44,riskLbl:'Low',ret3y:5.1,ret1y:5.6,ret30:0.4,ret90:1.2,consistency:95,followers:1220,watchers:300,
   alloc:[{k:'Bonds',v:50},{k:'Equity',v:26},{k:'Gold',v:10},{k:'Cash',v:14}],
   sectors:[{k:'Broad',v:100}],
   geo:[{k:'North America',v:54},{k:'Europe',v:26},{k:'Asia-Pacific',v:14},{k:'Emerging',v:6}],
   mcap:[{k:'Mega',v:52},{k:'Large',v:32},{k:'Mid',v:12},{k:'Small',v:4}],
   holdings:[{n:'Short & Intermediate Bonds',v:50},{n:'Dividend Equity',v:26},{n:'Gold',v:10},{n:'Cash',v:14}],
   summary:'The most conservative member: a 9% worst drawdown across 16 years and the top behaviour score. Prioritises not losing money over growing it fast.',
   philosophy:'Protect capital first, accept modest growth, sleep well.',
   timeline:[['8y ago','Shifted to capital preservation'],['3y ago','Added a gold hedge'],['1y ago','Kept a high cash buffer']],
   changes:[['Raised cash buffer','7 months ago']],
   risk:{sharpe:0.86,vol:6,maxDD:-9,beta:0.34}}),
 C({id:'c11',name:'Investor #6698',initials:'66',c1:'#F7931A',c2:'#B8690A',style:'Crypto-Forward Balanced',cat:'Crypto',
   match:54,badge:'Long-Term Investor',riskAdj:0.64,maxDD:-44,vol:29,behaviour:78,divers:56,years:6,shariah:false,overlap:33,riskLbl:'Very High',ret3y:18.9,ret1y:26.2,ret30:-2.4,ret90:4.7,consistency:58,followers:4130,watchers:1580,
   alloc:[{k:'Crypto',v:40},{k:'Global Equity',v:40},{k:'Cash / Stable',v:20}],
   sectors:[{k:'Technology',v:34},{k:'Financials',v:12},{k:'Digital Assets',v:40},{k:'Other',v:14}],
   geo:[{k:'North America',v:58},{k:'Global / Crypto',v:40},{k:'Other',v:2}],
   mcap:[{k:'Mega',v:40},{k:'Large',v:26},{k:'Digital',v:34}],
   holdings:[{n:'Bitcoin',v:24},{n:'Ethereum',v:12},{n:'Global Equity',v:40},{n:'Stablecoin yield',v:20},{n:'Other crypto',v:4}],
   summary:'Splits evenly between crypto and equities with a big stablecoin buffer. Strong recent returns but a 44% drawdown. Far more crypto than your DNA implies you want.',
   philosophy:'Treat crypto as a serious sleeve, balance it with equities and stable yield.',
   timeline:[['4y ago','Grew crypto to a full sleeve'],['2y ago','Added stablecoin income'],['5m ago','Rebalanced after a crypto rally']],
   changes:[['Rebalanced crypto sleeve','5 months ago']],
   risk:{sharpe:0.64,vol:29,maxDD:-44,beta:1.35}}),
 C({id:'c12',name:'Investor #1902',initials:'19',c1:'#4FC3F7',c2:'#1E88E5',style:'Endowment-Style Diversified',cat:'Balanced',
   match:83,badge:'Diversification Expert',riskAdj:1.0,maxDD:-18,vol:11,behaviour:88,divers:92,years:11,shariah:false,overlap:49,riskLbl:'Moderate',ret3y:9.7,ret1y:11.9,ret30:0.9,ret90:2.5,consistency:89,followers:2050,watchers:560,
   alloc:[{k:'Global Equity',v:50},{k:'REITs / Real assets',v:20},{k:'Bonds & TIPS',v:20},{k:'Cash',v:10}],
   sectors:[{k:'Technology',v:24},{k:'Financials',v:16},{k:'Real Estate',v:20},{k:'Healthcare',v:12},{k:'Industrials',v:14},{k:'Other',v:14}],
   geo:[{k:'North America',v:44},{k:'Europe',v:20},{k:'Asia-Pacific',v:22},{k:'Emerging',v:14}],
   mcap:[{k:'Mega',v:38},{k:'Large',v:32},{k:'Mid',v:20},{k:'Small',v:10}],
   holdings:[{n:'Global Equity',v:34},{n:'US Equity',v:16},{n:'REITs',v:20},{n:'Treasuries + TIPS',v:20},{n:'Cash',v:10}],
   summary:'A Swensen-style endowment build with the highest diversification in the community and real-asset exposure you currently lack. A strong, well-matched template to grow into.',
   philosophy:'Diversify across equity-like assets including real assets, harvest rebalancing premiums.',
   timeline:[['6y ago','Adopted an endowment-style model'],['3y ago','Added REITs and TIPS'],['7m ago','Rebalanced across sleeves']],
   changes:[['Added TIPS sleeve','7 months ago'],['REIT top-up','1 year ago']],
   risk:{sharpe:1.0,vol:11,maxDD:-18,beta:0.8}})
];

/* ============================================================
   INVESTMENT STRATEGIES - style-based, not tied to a person
   ============================================================ */
function S(o){ o.strategy=true; o.inspired=true; return o; }
const STRATEGIES = [
 S({id:'ai-infra',name:'AI Infrastructure',cat:'Growth',icon:'🤖',c1:'#7C6CFF',c2:'#5B21B6',risk:'High',vol:26,ret:'13-18% target',maxDD:-40,horizon:'7+ years',shariah:false,
   explain:'Owns the compute, chips, data-centre and energy backbone powering artificial intelligence, rather than betting on one application winner.',
   suit:'Growth investors who believe AI is a multi-decade build-out and can tolerate high volatility.',
   holdings:[{n:'Semiconductor leaders',v:34},{n:'Cloud & data centres',v:24},{n:'AI power & cooling',v:16},{n:'Networking',v:14},{n:'Cash',v:12}],
   alloc:[{k:'Equity',v:88},{k:'Cash',v:12}],
   tara:'A concentrated thematic bet. Exciting, but it moves hard. Cap it as a satellite and pair it with a diversified core.'}),
 S({id:'dividend',name:'Dividend Income',cat:'Income',icon:'💵',c1:'#E7C27D',c2:'#C9A24B',risk:'Low-Moderate',vol:10,ret:'6-9% target',maxDD:-16,horizon:'5+ years',shariah:false,
   explain:'Focuses on established companies with a long record of paying and growing dividends, for steady income plus modest growth.',
   suit:'Income seekers and cautious investors who value cash flow and lower volatility.',
   holdings:[{n:'Dividend Aristocrats',v:44},{n:'High-dividend equity',v:24},{n:'REITs',v:12},{n:'Bonds',v:14},{n:'Cash',v:6}],
   alloc:[{k:'Equity',v:68},{k:'REITs',v:12},{k:'Bonds',v:14},{k:'Cash',v:6}],
   tara:'A calmer, income-first tilt. Would raise the yield and lower the volatility of your current mix.'}),
 S({id:'inflation',name:'Inflation Protection',cat:'Defensive',icon:'🛡️',c1:'#34D399',c2:'#047857',risk:'Moderate',vol:11,ret:'5-8% target',maxDD:-14,horizon:'5+ years',shariah:false,
   explain:'Blends assets that historically hold value when prices rise: inflation-linked bonds, real assets, commodities and gold.',
   suit:'Investors worried about the erosion of cash and long bonds in an inflationary world.',
   holdings:[{n:'TIPS / index-linked bonds',v:34},{n:'Commodities',v:20},{n:'Gold',v:16},{n:'Real assets / REITs',v:20},{n:'Cash',v:10}],
   alloc:[{k:'Inflation-linked bonds',v:34},{k:'Real assets',v:36},{k:'Gold',v:16},{k:'Cash',v:14}],
   tara:'Your portfolio is light on inflation hedges. This sleeve adds protection that pure stocks and nominal bonds do not.'}),
 S({id:'defensive',name:'Defensive Allocation',cat:'Defensive',icon:'⚓',c1:'#607D8B',c2:'#37474F',risk:'Low',vol:8,ret:'4-7% target',maxDD:-11,horizon:'3+ years',shariah:false,
   explain:'A capital-preservation mix weighted toward bonds, defensive equities and cash to limit drawdowns.',
   suit:'Cautious investors, or anyone wanting to de-risk part of a portfolio before a goal.',
   holdings:[{n:'Short & intermediate bonds',v:44},{n:'Defensive equity',v:26},{n:'Gold',v:10},{n:'Cash',v:20}],
   alloc:[{k:'Bonds',v:44},{k:'Equity',v:26},{k:'Gold',v:10},{k:'Cash',v:20}],
   tara:'A good shock absorber. Useful for money you will need sooner, or to steady a growth-heavy plan.'}),
 S({id:'global-core',name:'Global ETF Core',cat:'Balanced',icon:'🌍',c1:'#00C389',c2:'#009E70',risk:'Moderate',vol:13,ret:'7-10% target',maxDD:-22,horizon:'7+ years',shariah:false,
   explain:'A simple, low-cost core of broad global equity and bond ETFs. The foundation most plans should be built on.',
   suit:'Almost everyone as a long-term core holding.',
   holdings:[{n:'Total World Equity',v:60},{n:'US Total Market',v:12},{n:'Global Aggregate Bonds',v:24},{n:'Cash',v:4}],
   alloc:[{k:'Global Equity',v:72},{k:'Bonds',v:24},{k:'Cash',v:4}],
   tara:'The strongest match for your DNA and the cheapest way to be truly diversified. A sensible anchor for your plan.'}),
 S({id:'emerging',name:'Emerging Markets',cat:'Growth',icon:'📈',c1:'#38BDF8',c2:'#0284C7',risk:'High',vol:22,ret:'9-14% target',maxDD:-34,horizon:'7+ years',shariah:false,
   explain:'Tilts toward faster-growing developing economies for higher long-run growth potential and diversification away from the US.',
   suit:'Long-horizon growth investors who can handle currency and political volatility.',
   holdings:[{n:'Broad Emerging Markets',v:50},{n:'Asia ex-Japan',v:20},{n:'EM small-cap',v:10},{n:'EM bonds',v:12},{n:'Cash',v:8}],
   alloc:[{k:'EM Equity',v:80},{k:'EM Bonds',v:12},{k:'Cash',v:8}],
   tara:'Your portfolio is heavily North American. A measured EM tilt improves diversification, but size it for the extra volatility.'}),
 S({id:'shariah-growth',name:'Shariah Growth',cat:'Growth',icon:'☪',c1:'#00C389',c2:'#00E0A0',risk:'Moderate-High',vol:15,ret:'8-12% target',maxDD:-24,horizon:'7+ years',shariah:true,
   explain:'A Shariah-screened growth portfolio of compliant global equities, excluding interest-based finance and other non-compliant sectors.',
   suit:'Investors wanting growth strictly within Shariah screens.',
   holdings:[{n:'Shariah Global Equity',v:50},{n:'Shariah US Equity',v:26},{n:'Shariah Emerging',v:12},{n:'Gold',v:6},{n:'Cash',v:6}],
   alloc:[{k:'Shariah Equity',v:88},{k:'Gold',v:6},{k:'Cash',v:6}],
   tara:'Fully compliant and growth-tilted. If Shariah screening matters to you, this is a cleaner growth engine than your current mix.'}),
 S({id:'btc-treasury',name:'Bitcoin Treasury',cat:'Crypto',icon:'₿',c1:'#F7931A',c2:'#B8690A',risk:'Very High',vol:66,ret:'Highly variable',maxDD:-77,horizon:'7+ years',shariah:false,
   explain:'A Bitcoin-dominant allocation treating BTC as a long-term reserve asset, with a small stable buffer.',
   suit:'Long-horizon Bitcoin believers who can hold through 70%+ drawdowns.',
   holdings:[{n:'Bitcoin',v:90},{n:'Stablecoin',v:10}],
   alloc:[{k:'Bitcoin',v:90},{k:'Stable',v:10}],
   tara:'Extremely volatile and concentrated. Only ever a small satellite for most plans. Never money you need soon.'}),
 S({id:'eth-eco-s',name:'Ethereum Ecosystem',cat:'Crypto',icon:'Ξ',c1:'#627EEA',c2:'#3C5BD6',risk:'Very High',vol:72,ret:'Highly variable',maxDD:-79,horizon:'7+ years',shariah:false,
   explain:'Exposure to Ethereum, staking and layer-2 scaling as a bet on the smart-contract economy.',
   suit:'High-risk investors bullish on decentralised applications who want staking yield.',
   holdings:[{n:'Ethereum',v:60},{n:'Staked ETH',v:15},{n:'Layer-2 tokens',v:18},{n:'Stable',v:7}],
   alloc:[{k:'Ethereum',v:75},{k:'Layer-2',v:18},{k:'Stable',v:7}],
   tara:'Staking adds yield but not safety. A thematic satellite, not a core, for a Balanced Builder.'}),
 S({id:'web3',name:'Web3 Infrastructure',cat:'Crypto',icon:'🔗',c1:'#7C6CFF',c2:'#5B21B6',risk:'Extreme',vol:88,ret:'Highly variable',maxDD:-85,horizon:'7+ years',shariah:false,
   explain:'A venture-style basket of blockchain infrastructure and emerging protocols. High risk, high dispersion.',
   suit:'Risk-seeking investors using money they can fully afford to lose.',
   holdings:[{n:'ETH / SOL',v:40},{n:'Infrastructure tokens',v:35},{n:'Emerging protocols',v:20},{n:'Stable',v:5}],
   alloc:[{k:'Large-cap infra',v:40},{k:'Mid & emerging',v:55},{k:'Stable',v:5}],
   tara:'The highest-risk strategy here. Treat it like venture capital: tiny size, long horizon, expect failures.'}),
 S({id:'income-focus',name:'Income Focus',cat:'Income',icon:'🏦',c1:'#E7C27D',c2:'#B8860B',risk:'Low-Moderate',vol:9,ret:'5-8% target',maxDD:-13,horizon:'3+ years',shariah:false,
   explain:'Maximises reliable income across dividend equities, bonds, REITs and credit while keeping volatility low.',
   suit:'Investors who want regular cash flow, including those near or in retirement.',
   holdings:[{n:'Dividend equity',v:34},{n:'Investment-grade bonds',v:30},{n:'REITs',v:16},{n:'High-yield credit',v:12},{n:'Cash',v:8}],
   alloc:[{k:'Equity',v:34},{k:'Bonds',v:42},{k:'REITs',v:16},{k:'Cash',v:8}],
   tara:'An income engine with a smooth ride. Suits money you want to draw from rather than grow aggressively.'}),
 S({id:'high-growth',name:'High Growth',cat:'Growth',icon:'🚀',c1:'#FF7A9A',c2:'#DB2777',risk:'Very High',vol:30,ret:'12-20% target',maxDD:-45,horizon:'10+ years',shariah:false,
   explain:'A concentrated, aggressive growth portfolio for maximum long-run upside, accepting deep drawdowns.',
   suit:'Young, aggressive investors with a very long horizon and steady nerves.',
   holdings:[{n:'Growth equity',v:50},{n:'Innovation themes',v:22},{n:'Emerging markets',v:12},{n:'Crypto',v:8},{n:'Cash',v:8}],
   alloc:[{k:'Growth Equity',v:84},{k:'Crypto',v:8},{k:'Cash',v:8}],
   tara:'High potential, high pain. A poor match unless your horizon is very long and you truly hold through 40% drops.'}),
 S({id:'low-vol',name:'Low Volatility',cat:'Defensive',icon:'📉',c1:'#4FC3F7',c2:'#1D4ED8',risk:'Low',vol:8,ret:'5-8% target',maxDD:-12,horizon:'3+ years',shariah:false,
   explain:'Selects lower-volatility equities and bonds to deliver equity-like growth with a smoother path.',
   suit:'Nervous investors who want to stay invested without the full swings of the market.',
   holdings:[{n:'Min-volatility equity',v:52},{n:'Quality bonds',v:30},{n:'Gold',v:8},{n:'Cash',v:10}],
   alloc:[{k:'Low-vol Equity',v:52},{k:'Bonds',v:30},{k:'Gold',v:8},{k:'Cash',v:10}],
   tara:'A gentler path to growth. If volatility tempts you to sell, this style helps you stay the course.'}),
 S({id:'sustainable',name:'Sustainable Investing',cat:'Balanced',icon:'🌱',c1:'#34D399',c2:'#059669',risk:'Moderate',vol:14,ret:'7-10% target',maxDD:-23,horizon:'7+ years',shariah:false,esg:true,
   explain:'A diversified ESG-screened portfolio favouring companies with strong environmental, social and governance practices.',
   suit:'Investors who want market-like returns aligned with sustainability values.',
   holdings:[{n:'ESG Global Equity',v:56},{n:'Green bonds',v:22},{n:'Clean energy',v:12},{n:'Cash',v:10}],
   alloc:[{k:'ESG Equity',v:68},{k:'Green Bonds',v:22},{k:'Cash',v:10}],
   tara:'Values-aligned and broadly diversified. Returns track the market closely, so you sacrifice little for the screen.'})
];

/* everything searchable in one place */
const ALL_LEGENDS = TRADFI.concat(CRYPTO);
